#' Process tracing estimator
#'
#' Draw conclusions from a model given a query, data, and process tracing strategies
#'
#' See https://book.declaredesign.org/observational-causal.html#process-tracing
#'
#' @param causal_model a model generated by `CausalQueries`
#' @param data a single row dataset with data on nodes in the model
#' @param query a causal query of interest
#' @param strategies a list of sets of nodes examined
#'
#' @return a data.frame of estimates
#'
#' @export
#'
process_tracing_estimator <- function(causal_model, query, data, strategies) {

  if(!requireNamespace("CausalQueries")){
    message("The process_tracing_estimator function requires the 'CausalQueries' package.")
    return(invisible())
  }

  causal_model %>%
    CausalQueries::query_model(query = query,
                               given = CausalQueries::strategy_statements(data, strategies)) %>%
    select(estimate = mean) %>%
    mutate(XY = paste0("X", data$X, "Y", data$Y),
           term = strategies %>% lapply(paste, collapse = "-") %>% unlist)

}

#' Generate lags in grouped data
#'
#' See https://book.declaredesign.org/observational-causal.html#difference-in-differences
#'
#' @param x Vector of values
#' @param groups Grouping variable
#' @param n Positive integer of length 1, giving the number of positions to lead or lag by
#' @param order_by Ordering variable withing group (e.g., time)
#' @param default Value used for non-existent rows. Defaults to NA.
#'
#' @return vector of lagged values
#'
#' @export
#'
#' @importFrom tibble tibble
#' @importFrom rlang enexpr `:=` `!!`
#' @importFrom dplyr group_by mutate ungroup pull lag `%>%`
#'
#'
lag_by_group <- function(x, groups, n = 1, order_by, default = NA) {
  x_nm <- enexpr(x)
  grp_nm <- enexpr(groups)
  tibble(!!x_nm := x, !!grp_nm := groups, order_by___ = order_by) %>%
    group_by(!!grp_nm) %>%
    mutate(!!x_nm := lag(!!x_nm, n = n, default = default, order_by = order_by___)) %>%
    ungroup %>%
    pull(!!x_nm)
}

#' Tidy helper function for did_multiplegt
#'
#' Runs did_multiplegt estimation function and returns tidy data frame output
#'
#' See https://book.declaredesign.org/observational-causal.html#difference-in-differences
#'
#' @param data a data.frame
#' @param ... options passed to did_multiplegt
#'
#' @return a data.frame of estimates
#'
#' @export
#'
#' @importFrom tibble tibble
#'
did_multiplegt_tidy <- function(data, ...) {

  if(!requireNamespace("DIDmultiplegt")){
    message("The did_multiplegt_tidy function requires the 'DIDmultiplegt' package.")
    return(invisible())
  }

  fit <- DIDmultiplegt::did_multiplegt(df = data, ...)
  tibble(estimate = fit$effect)
}

#' Tidy helper function for rdrobust function
#'
#' Runs rdrobust estimation function and returns tidy data frame output
#'
#' See https://book.declaredesign.org/observational-causal.html#regression-discontinuity-designs
#'
#' @param fit Model fit object from rdrobust
#' @param conf.int
#'
#' @return a data.frame of estimates
#'
#' @export
tidy.rdrobust <- function(fit, ...) {
  if(!requireNamespace("rdrobust")){
    message("The rdrobust_tidy function requires the 'rdrobust' package.")
    return(invisible())
  }

  ret <- data.frame(rownames(fit$coef), fit$coef, fit$se, fit$z, fit$pv, fit$ci, c = fit$c)
  row.names(ret) <- NULL
  names(ret) <- c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high", "cutoff")

  ret
}


#' Helper function for using rdrobust as a model in `declare_estimator`
#'
#' @param data a data.frame
#' @param y unquoted name of the outcome variable
#' @param x unquoted name of the running variable
#' @param subset an optional vector specifying a subset of observations to be used in the fitting process
#' @param ...
#'
#' @importFrom dplyr filter
#' @importFrom rlang enquo `!!`
#'
#' @return rdrobust model fit object
#'
#' @export
rdrobust_helper <- function(data, y, x, subset = NULL, ...) {
  if(!missing(subset))
    data <- filter(data, !!enquo(subset))
  rdrobust::rdrobust(y = pull(data, {{y}}), x = pull(data, {{x}}), ... = ...)
}

