#' Process tracing estimator
#'
#' Draw conclusions from a model given a query, data, and process tracing strategies
#'
#' See https://book.declaredesign.org/observational-causal.html#process-tracing
#'
#' @param causal_model a model generated by `CausalQueries`
#' @param data a single row dataset with data on nodes in the model
#' @param query a causal query of interest
#' @param strategies a vector describing sets of nodes to be examined e.g. c("X", "X-Y")
#'
#' @return a data.frame of estimates
#'
#' @export
#' @examples
#'
#' process_tracing_estimator(
#'   CausalQueries::make_model("X -> Y"),
#'   "Y[X=1] > Y[X=0]",
#'   data.frame(X=1, Y = 1),
#'   "X-Y")
#'
process_tracing_estimator <- function(causal_model, query, data, strategies) {

  if(!requireNamespace("CausalQueries")){
    message("The process_tracing_estimator function requires the 'CausalQueries' package.")
    return(invisible())
  }

  strategy_elements <- strategies %>% lapply(function(x) strsplit(x, "-")[[1]])

  given <- strategy_statements(data, strategy_elements)

  causal_model %>%
    CausalQueries::query_model(query = query, given = given) %>%
    mutate(term = strategies, XY = paste0("X", data$X, "Y", data$Y)) %>%
    select(term, XY, estimate = mean)

}


#' Generate strategy statements given data
#'
#' Helper to generate statements of the form "X = 1 & Y = 0"
#' from realized data on one observation
#'
#' @param data A data frame with one row
#' @param strategies A list of strategies where each strategy
#'   is a set of nodes to be observed
#' @keywords helper
#' @export
#' @return A string
#' @examples
#'  data.frame(X = 1, M = 0, Y = NA) %>%
#'  strategy_statements(list(c("X", "M", "Y"), "X", "Y"))
#'
strategy_statements <- function(data, strategies){

  if(nrow(data) !=1) {
    stop("strategy_statements is designed for single row datasets")
  }

  if(!is.list(strategies)) {
    stop("please provide strategies within a list (e.g.(list(c('X', 'Y'))")
  }

  lapply(strategies, function(s)
    (sapply(s, function(x)
      paste(x, "==", data[x]))[sapply(s, function(x)
        ! is.na(data[x]))]) %>%
      paste(collapse = " & "))

}

